name: Test

on:
  push

jobs:
  gen-mytrix:
    name: Generate Mytrix
    runs-on: ubuntu-latest
    outputs:
      mytrix: ${{ steps.gen-mytrix.outputs.mytrix }}
    steps:
      - name: Gen mytrix
        id: gen-mytrix
        run: |
          echo 'mytrix=["a", "n"]' >> $GITHUB_OUTPUT
      - name: List all
        run: |
          echo '${{ steps.gen-mytrix.outputs.mytrix }}'

  mytrix-job:
    name: Run Mytrix Job
    runs-on: ubuntu-latest
    needs: gen-mytrix
    strategy:
      matrix:
        letters: ${{ fromJSON(needs.gen-mytrix.outputs.mytrix) }}
    steps:
      - name: Echo
        run: |
          echo ${{ matrix.letters }}
